# fly.toml app configuration file generated for journaly on 2024-04-28T22:16:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'journaly'
primary_region = 'ord'


[[services]]
internal_port = 3000
protocol = "tcp"

[[mounts]]
source = 'data'
destination = '/data'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
