# fly.toml app configuration file generated for yogi-journal on 2024-04-25T20:50:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yogi-journal'
primary_region = 'ord'
kill_signal = "SIGINT"
kill_timeout = 5
processes = ['app']

[build]

[[mounts]]
source = "data"
destination = "/data"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[checks]
[checks.status]
port = 3000
type = "http"
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/"
protocol = "http"
tls_skip_verify = false

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
